/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FuncionarioRouteImport } from './routes/funcionario'
import { Route as ClienteRouteImport } from './routes/cliente'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FuncionarioIndexRouteImport } from './routes/funcionario.index'
import { Route as ClienteIndexRouteImport } from './routes/cliente.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as FuncionarioSolicitacoesRouteImport } from './routes/funcionario.solicitacoes'
import { Route as ClientePerfilRouteImport } from './routes/cliente.perfil'
import { Route as ClienteHistoricoRouteImport } from './routes/cliente.historico'
import { Route as ClienteFidelidadeRouteImport } from './routes/cliente.fidelidade'
import { Route as ClienteBeneficiosRouteImport } from './routes/cliente.beneficios'
import { Route as ClienteAgendamentosRouteImport } from './routes/cliente.agendamentos'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminRelatoriosRouteImport } from './routes/admin.relatorios'
import { Route as AdminMarketingRouteImport } from './routes/admin.marketing'
import { Route as AdminFinanceiroRouteImport } from './routes/admin.financeiro'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminClientesRouteImport } from './routes/admin.clientes'
import { Route as AdminAssinaturasRouteImport } from './routes/admin.assinaturas'
import { Route as AdminAgendaRouteImport } from './routes/admin.agenda'

const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FuncionarioRoute = FuncionarioRouteImport.update({
  id: '/funcionario',
  path: '/funcionario',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteRoute = ClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FuncionarioIndexRoute = FuncionarioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FuncionarioRoute,
} as any)
const ClienteIndexRoute = ClienteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClienteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const FuncionarioSolicitacoesRoute = FuncionarioSolicitacoesRouteImport.update({
  id: '/solicitacoes',
  path: '/solicitacoes',
  getParentRoute: () => FuncionarioRoute,
} as any)
const ClientePerfilRoute = ClientePerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => ClienteRoute,
} as any)
const ClienteHistoricoRoute = ClienteHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => ClienteRoute,
} as any)
const ClienteFidelidadeRoute = ClienteFidelidadeRouteImport.update({
  id: '/fidelidade',
  path: '/fidelidade',
  getParentRoute: () => ClienteRoute,
} as any)
const ClienteBeneficiosRoute = ClienteBeneficiosRouteImport.update({
  id: '/beneficios',
  path: '/beneficios',
  getParentRoute: () => ClienteRoute,
} as any)
const ClienteAgendamentosRoute = ClienteAgendamentosRouteImport.update({
  id: '/agendamentos',
  path: '/agendamentos',
  getParentRoute: () => ClienteRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRelatoriosRoute = AdminRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketingRoute = AdminMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceiroRoute = AdminFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssinaturasRoute = AdminAssinaturasRouteImport.update({
  id: '/assinaturas',
  path: '/assinaturas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgendaRoute = AdminAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/cliente': typeof ClienteRouteWithChildren
  '/funcionario': typeof FuncionarioRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/assinaturas': typeof AdminAssinaturasRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/cliente/agendamentos': typeof ClienteAgendamentosRoute
  '/cliente/beneficios': typeof ClienteBeneficiosRoute
  '/cliente/fidelidade': typeof ClienteFidelidadeRoute
  '/cliente/historico': typeof ClienteHistoricoRoute
  '/cliente/perfil': typeof ClientePerfilRoute
  '/funcionario/solicitacoes': typeof FuncionarioSolicitacoesRoute
  '/admin/': typeof AdminIndexRoute
  '/cliente/': typeof ClienteIndexRoute
  '/funcionario/': typeof FuncionarioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/assinaturas': typeof AdminAssinaturasRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/cliente/agendamentos': typeof ClienteAgendamentosRoute
  '/cliente/beneficios': typeof ClienteBeneficiosRoute
  '/cliente/fidelidade': typeof ClienteFidelidadeRoute
  '/cliente/historico': typeof ClienteHistoricoRoute
  '/cliente/perfil': typeof ClientePerfilRoute
  '/funcionario/solicitacoes': typeof FuncionarioSolicitacoesRoute
  '/admin': typeof AdminIndexRoute
  '/cliente': typeof ClienteIndexRoute
  '/funcionario': typeof FuncionarioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/cliente': typeof ClienteRouteWithChildren
  '/funcionario': typeof FuncionarioRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/assinaturas': typeof AdminAssinaturasRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/cliente/agendamentos': typeof ClienteAgendamentosRoute
  '/cliente/beneficios': typeof ClienteBeneficiosRoute
  '/cliente/fidelidade': typeof ClienteFidelidadeRoute
  '/cliente/historico': typeof ClienteHistoricoRoute
  '/cliente/perfil': typeof ClientePerfilRoute
  '/funcionario/solicitacoes': typeof FuncionarioSolicitacoesRoute
  '/admin/': typeof AdminIndexRoute
  '/cliente/': typeof ClienteIndexRoute
  '/funcionario/': typeof FuncionarioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cadastro'
    | '/cliente'
    | '/funcionario'
    | '/login'
    | '/logout'
    | '/admin/agenda'
    | '/admin/assinaturas'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/financeiro'
    | '/admin/marketing'
    | '/admin/relatorios'
    | '/admin/usuarios'
    | '/cliente/agendamentos'
    | '/cliente/beneficios'
    | '/cliente/fidelidade'
    | '/cliente/historico'
    | '/cliente/perfil'
    | '/funcionario/solicitacoes'
    | '/admin/'
    | '/cliente/'
    | '/funcionario/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/login'
    | '/logout'
    | '/admin/agenda'
    | '/admin/assinaturas'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/financeiro'
    | '/admin/marketing'
    | '/admin/relatorios'
    | '/admin/usuarios'
    | '/cliente/agendamentos'
    | '/cliente/beneficios'
    | '/cliente/fidelidade'
    | '/cliente/historico'
    | '/cliente/perfil'
    | '/funcionario/solicitacoes'
    | '/admin'
    | '/cliente'
    | '/funcionario'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cadastro'
    | '/cliente'
    | '/funcionario'
    | '/login'
    | '/logout'
    | '/admin/agenda'
    | '/admin/assinaturas'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/financeiro'
    | '/admin/marketing'
    | '/admin/relatorios'
    | '/admin/usuarios'
    | '/cliente/agendamentos'
    | '/cliente/beneficios'
    | '/cliente/fidelidade'
    | '/cliente/historico'
    | '/cliente/perfil'
    | '/funcionario/solicitacoes'
    | '/admin/'
    | '/cliente/'
    | '/funcionario/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  ClienteRoute: typeof ClienteRouteWithChildren
  FuncionarioRoute: typeof FuncionarioRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funcionario': {
      id: '/funcionario'
      path: '/funcionario'
      fullPath: '/funcionario'
      preLoaderRoute: typeof FuncionarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente': {
      id: '/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof ClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funcionario/': {
      id: '/funcionario/'
      path: '/'
      fullPath: '/funcionario/'
      preLoaderRoute: typeof FuncionarioIndexRouteImport
      parentRoute: typeof FuncionarioRoute
    }
    '/cliente/': {
      id: '/cliente/'
      path: '/'
      fullPath: '/cliente/'
      preLoaderRoute: typeof ClienteIndexRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/funcionario/solicitacoes': {
      id: '/funcionario/solicitacoes'
      path: '/solicitacoes'
      fullPath: '/funcionario/solicitacoes'
      preLoaderRoute: typeof FuncionarioSolicitacoesRouteImport
      parentRoute: typeof FuncionarioRoute
    }
    '/cliente/perfil': {
      id: '/cliente/perfil'
      path: '/perfil'
      fullPath: '/cliente/perfil'
      preLoaderRoute: typeof ClientePerfilRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/cliente/historico': {
      id: '/cliente/historico'
      path: '/historico'
      fullPath: '/cliente/historico'
      preLoaderRoute: typeof ClienteHistoricoRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/cliente/fidelidade': {
      id: '/cliente/fidelidade'
      path: '/fidelidade'
      fullPath: '/cliente/fidelidade'
      preLoaderRoute: typeof ClienteFidelidadeRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/cliente/beneficios': {
      id: '/cliente/beneficios'
      path: '/beneficios'
      fullPath: '/cliente/beneficios'
      preLoaderRoute: typeof ClienteBeneficiosRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/cliente/agendamentos': {
      id: '/cliente/agendamentos'
      path: '/agendamentos'
      fullPath: '/cliente/agendamentos'
      preLoaderRoute: typeof ClienteAgendamentosRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/relatorios': {
      id: '/admin/relatorios'
      path: '/relatorios'
      fullPath: '/admin/relatorios'
      preLoaderRoute: typeof AdminRelatoriosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketing': {
      id: '/admin/marketing'
      path: '/marketing'
      fullPath: '/admin/marketing'
      preLoaderRoute: typeof AdminMarketingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/financeiro': {
      id: '/admin/financeiro'
      path: '/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AdminFinanceiroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assinaturas': {
      id: '/admin/assinaturas'
      path: '/assinaturas'
      fullPath: '/admin/assinaturas'
      preLoaderRoute: typeof AdminAssinaturasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agenda': {
      id: '/admin/agenda'
      path: '/agenda'
      fullPath: '/admin/agenda'
      preLoaderRoute: typeof AdminAgendaRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAgendaRoute: typeof AdminAgendaRoute
  AdminAssinaturasRoute: typeof AdminAssinaturasRoute
  AdminClientesRoute: typeof AdminClientesRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminFinanceiroRoute: typeof AdminFinanceiroRoute
  AdminMarketingRoute: typeof AdminMarketingRoute
  AdminRelatoriosRoute: typeof AdminRelatoriosRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAgendaRoute: AdminAgendaRoute,
  AdminAssinaturasRoute: AdminAssinaturasRoute,
  AdminClientesRoute: AdminClientesRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminFinanceiroRoute: AdminFinanceiroRoute,
  AdminMarketingRoute: AdminMarketingRoute,
  AdminRelatoriosRoute: AdminRelatoriosRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ClienteRouteChildren {
  ClienteAgendamentosRoute: typeof ClienteAgendamentosRoute
  ClienteBeneficiosRoute: typeof ClienteBeneficiosRoute
  ClienteFidelidadeRoute: typeof ClienteFidelidadeRoute
  ClienteHistoricoRoute: typeof ClienteHistoricoRoute
  ClientePerfilRoute: typeof ClientePerfilRoute
  ClienteIndexRoute: typeof ClienteIndexRoute
}

const ClienteRouteChildren: ClienteRouteChildren = {
  ClienteAgendamentosRoute: ClienteAgendamentosRoute,
  ClienteBeneficiosRoute: ClienteBeneficiosRoute,
  ClienteFidelidadeRoute: ClienteFidelidadeRoute,
  ClienteHistoricoRoute: ClienteHistoricoRoute,
  ClientePerfilRoute: ClientePerfilRoute,
  ClienteIndexRoute: ClienteIndexRoute,
}

const ClienteRouteWithChildren =
  ClienteRoute._addFileChildren(ClienteRouteChildren)

interface FuncionarioRouteChildren {
  FuncionarioSolicitacoesRoute: typeof FuncionarioSolicitacoesRoute
  FuncionarioIndexRoute: typeof FuncionarioIndexRoute
}

const FuncionarioRouteChildren: FuncionarioRouteChildren = {
  FuncionarioSolicitacoesRoute: FuncionarioSolicitacoesRoute,
  FuncionarioIndexRoute: FuncionarioIndexRoute,
}

const FuncionarioRouteWithChildren = FuncionarioRoute._addFileChildren(
  FuncionarioRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CadastroRoute: CadastroRoute,
  ClienteRoute: ClienteRouteWithChildren,
  FuncionarioRoute: FuncionarioRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
